server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/notifications

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ecommerce.notificationservice.dto.OrderEvent